CREATE DATABASE IF NOT EXISTS bbs
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE bbs;

CREATE TABLE IF NOT EXISTS user(
	user_id VARCHAR(32) PRIMARY KEY COMMENT 'pk'
	id VARCHAR(32) NOT NULL,
	nickname VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	birth VARCHAR(32) NOT NULL,
	register_date DATE DEFAULT=NOW()
);
